

services:
  backend:
    build: ./backend
    container_name: laravel_app
    restart: always
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
  apache:
    image: apache:alpine
    container_name: apache_server
    restart: always
    ports:
      - "8002:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: laravel
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    build: ./frontend
    container_name: react_app
    restart: always
    ports:
      - "3000:3000"

  phpmyadmin:
    image: phpmyadmin:lastet
    restart: always
 
    