name: Deploy Laravel + ReactJS to VPS

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: 📤 Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: | 
            cd /var/www/duantotnghiep
            git reset --hard HEAD
            git pull origin develop
            sudo docker compose -f docker-compose.prod.yml down
            sudo docker system prune -af
            sudo docker compose -f docker-compose.prod.yml build --no-cache
            sudo docker compose -f docker-compose.prod.yml up -d

